version: '4.2'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}  # Set a strong password
      GF_USERS_DEFAULT_ORG_ROLE: Editor  # Optional: Default user role
      GF_DEFAULT_APP_NAME: ${GRAFANA_ADMIN_USER:-admin}  # Optional: Set app name for dashboards

volumes:
  prometheus-data:
  grafana-data: