global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          # - "172.20.60.198:5500"
          - "${PROMETHEUS_TARGET_ENV_VAR:-172.20.60.198:5500}"
